Repository BloodFutur/geicar, pull requests merged in 2024-11, with the labels that each got.

#10 Add dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  general/dev_container.md
Labels: Environment

#25 Add new python script to periodically capture images with the camera
  ImageCapture/webcam_image_capture.py
Labels: License plate and detection analysis

#26 5: Parking map website
  jetsonNano/ros2_ws/.gitignore
  raspberryPI3/ros2_ws/src/geicar_start/launch/geicar.launch.py
  raspberryPI3/ros2_ws/src/geicar_start/package.xml
  website/data/gps_nov13_cloudy_part1.csv
  website/data/gps_nov13_cloudy_part2.csv
  website/data/gps_nov13_cloudy_part3.csv
  website/data/gps_nov13_cloudy_part4.csv
  website/data/gps_nov15_sunny_1.csv
  website/data/gps_nov15_sunny_2straightback.csv
  website/index.html
  website/js/gps.js
  website/js/map.js
  website/js/ros.js
  website/style.css
Labels: Automated Parking Management

#46 feat-34: Add tests to CI
  .github/workflows/ci.yml
  raspberryPI3/ros2_ws/src/can/package.xml
  raspberryPI3/ros2_ws/src/car_control/package.xml
  raspberryPI3/ros2_ws/src/carla_msgs/package.xml
  raspberryPI3/ros2_ws/src/geicar_start/package.xml
  raspberryPI3/ros2_ws/src/interfaces/package.xml
  raspberryPI3/ros2_ws/src/joystick/package.xml
  raspberryPI3/ros2_ws/src/simulation/package.xml
  raspberryPI3/ros2_ws/src/system_check/package.xml
Labels: Environment

#31 feat-21: Detect obstacles with ultrasonic sensors
  .devcontainer/devcontainer.json
  raspberryPI3/ros2_ws/src/detection/LICENSE
  raspberryPI3/ros2_ws/src/detection/Readme.md
  raspberryPI3/ros2_ws/src/detection/detection/__init__.py
  raspberryPI3/ros2_ws/src/detection/detection/__pycache__/__init__.cpython-310.pyc
  raspberryPI3/ros2_ws/src/detection/detection/__pycache__/obstacles_detection.cpython-310.pyc
  raspberryPI3/ros2_ws/src/detection/detection/obstacles_detection_lib.py
  raspberryPI3/ros2_ws/src/detection/detection/obstacles_detection_node.py
  raspberryPI3/ros2_ws/src/detection/package.xml
  raspberryPI3/ros2_ws/src/detection/resource/detection
  raspberryPI3/ros2_ws/src/detection/setup.cfg
  raspberryPI3/ros2_ws/src/detection/setup.py
  raspberryPI3/ros2_ws/src/detection/test/test_obstacles_detection_wip.py
  raspberryPI3/ros2_ws/src/detection/test/test_unit_obstacles_detection.py
Labels: Safety

#51 bug-32: Add automatic time/date synchronization
  raspberryPI3/configuration_files/time_update.sh
  raspberryPI3/initial_configuration.md
Labels: Environment

#53 feat-50: Add parking slots to the website map
  website/js/map.js
Labels: Automated Parking Management

#55 Feat 27 : add emergency stop if there is an obstacle
  raspberryPI3/ros2_ws/src/car_control/src/car_control_node.cpp
  raspberryPI3/ros2_ws/src/detection/Readme.md
  raspberryPI3/ros2_ws/src/detection/detection/obstacles_detection_node.py
  raspberryPI3/ros2_ws/src/geicar_start/launch/geicar.launch.py
Labels: Safety

#57 40 integrate ai model ros2
  jetsonNano/ros2_ws/src/geicar_start_jetson/launch/geicar.jetson.launch.py
  jetsonNano/ros2_ws/src/usb_cam/CMakeLists.txt
  jetsonNano/ros2_ws/src/usb_cam/README.md
  jetsonNano/ros2_ws/src/usb_cam/scripts/plate_detection.py
Labels: License plate and detection analysis
