Repository BloodFutur/geicar, pull requests merged in 2024-12, with the labels that each got.

#72 Feature: Cropping image according to bounding boxes detected by Yolo
  ImageCapture/cropped_images/eu1_crop_396_340.png
  ImageCapture/cropped_images/eu2_crop_141_259.png
  ImageCapture/cropped_images/eu3_crop_348_185.png
  ImageCapture/image_crop.py
  ImageCapture/test_crop/eu1.jpg
  ImageCapture/test_crop/eu2.jpg
  ImageCapture/test_crop/eu3.jpg
  ImageCapture/test_crop/test_crop.xml
Labels: License plate and detection analysis

#74 Feature 62: Website add real time video stream
  jetsonNano/ros2_ws/src/usb_cam/scripts/plate_detection.py
  website/index.html
  website/js/ros.js
Labels: Automated Parking Management

#77 Change frame_id value of /imu_data to "base_link"
  raspberryPI3/ros2_ws/src/can/src/can_rx_node.cpp
  raspberryPI3/ros2_ws/src/geicar_start/launch/geicar.launch.py
  raspberryPI3/ros2_ws/src/imu_tools/imu_filter_madgwick/CMakeLists.txt
  raspberryPI3/ros2_ws/src/imu_tools/imu_filter_madgwick/config/imu_filter.yaml
  raspberryPI3/ros2_ws/src/imu_tools/imu_filter_madgwick/src/imu_filter_ros.cpp
  raspberryPI3/ros2_ws/src/imu_tools/imu_filter_madgwick/src/imu_frame_id_modifier.cpp
Labels: Trajectory control

#78 Integrate robot_localization in the project and estimate the car's position with IMU and Encoder data
  raspberryPI3/ros2_ws/src/can/CMakeLists.txt
  raspberryPI3/ros2_ws/src/can/include/can/can.h
  raspberryPI3/ros2_ws/src/can/package.xml
  raspberryPI3/ros2_ws/src/can/src/can_rx_node.cpp
  raspberryPI3/ros2_ws/src/geicar_start/CMakeLists.txt
  raspberryPI3/ros2_ws/src/geicar_start/config/ekf_config.yaml
  raspberryPI3/ros2_ws/src/geicar_start/launch/geicar.launch.py
  raspberryPI3/ros2_ws/src/imu_tools/imu_complementary_filter/src/complementary_filter_ros.cpp
  raspberryPI3/ros2_ws/src/rosbag_data/db3/GPS_IMU.db3
  raspberryPI3/ros2_ws/src/rosbag_data/db3/IMU.db3
  raspberryPI3/ros2_ws/src/rosbag_data/filtered_odometry_positions.csv
  raspberryPI3/ros2_ws/src/rosbag_data/filtered_odometry_positions_IMU.csv
  raspberryPI3/ros2_ws/src/rosbag_data/odometry.db3
  raspberryPI3/ros2_ws/src/rosbag_data/odometry_GPS_IMU.db3
  raspberryPI3/ros2_ws/src/rosbag_data/traj_courbe_kalman.csv
  raspberryPI3/ros2_ws/src/rosbag_data/traj_courbe_kalman.db3
Labels: Trajectory control

#87 Create a set speed function in car_control node
  raspberryPI3/ros2_ws/src/car_control/src/car_control_node.cpp
Labels: Trajectory control
