Repository BloodFutur/geicar, pull requests merged in 2025-01, with the labels that each got.

#89 bug-88: Fix mqtt_client not launched correctly
  raspberryPI3/ros2_ws/src/geicar_start/launch/geicar.launch.py
Labels: Bug

#100 Final clean Version of Character Extraction using Char Segmentation
  PlaqueDetection/Char_Extraction_With_Segmentation/Character_Extraction.py
  PlaqueDetection/Char_Extraction_With_Segmentation/Segmentor.py
  PlaqueDetection/Char_Extraction_With_Segmentation/Tilt_Corrector.py
  PlaqueDetection/Char_Extraction_With_Segmentation/__pycache__/Segmentor.cpython-311.pyc
  PlaqueDetection/Char_Extraction_With_Segmentation/__pycache__/Tilt_Corrector.cpython-311.pyc
  PlaqueDetection/Char_Extraction_With_Segmentation/__pycache__/detect.cpython-311.pyc
  PlaqueDetection/Char_Extraction_With_Segmentation/detect.py
Labels: Enhancement

#108 Tried to change Ubuntu version for github action
  .github/workflows/ci.yml
Labels: Bug, Environment
